### ISSUE TITLE
Wildcard search doesn't work for Windows

### ISSUE THREAD

**Issue by muting** [paragi/rocket-store-node#10]
First of all, thanks for this helpful tool!
While testing on a Windows10x64, I found the get wildcard search to be not working.
i.e. when searching for  '*llo*' to get the key 'hello', it won't return it.
So I looked into the code, and found the following:
on rocket-store.js:190, fileNameWash() is called, which in turn calls sanitize() from [sanitize-filename](https://www.npmjs.com/package/sanitize-filename) in case where the system is Windows.
Based from their doc, reserved characters ( /, **?**, <, >, \\, :, **\***, |, and " ) are removed. So '*' or '?' are gone from here afterwards.
This causes the wildcard check from line 195 to always return false, unless the key is empty:
`let wildcard = key.indexOf('*') > -1 || key.indexOf('?') > -1 || !key.length;`

Please correct me if I'm incorrect or missed anything, but I think sanitize() needs to be replaced with a regex expression or another package with customizable sanitize (haven't found any yet)

**Comment by paragi** [comment]
Thank you for reporting this.
It's a good suggestion. I will look into to it.

**Comment by muting** [comment]
Thank you for the quick fix! Tested and OK

**Comment by muting** [comment]
After doing a fresh install, I noticed rocket-store.js:49 
`const sanitize = require("sanitize-filename");`
is still there.

**Comment by cp-helsinge** [comment]
Thank you for reporting this.
It has been removed

**Comment by paragi** [comment]
done
